// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lswggtsznuewamnhsvvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzd2dndHN6bnVld2FtbmhzdnZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDY3MjMsImV4cCI6MjA2OTM4MjcyM30.XMeKkD-7H7nkmK64FJwVjCEbgpFG06PJQflveFESrbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});